site_url : https://asalvadorc.github.io/AD_Componentes

site_name: AD - AccÃ©s a Dades


extra_css:
  - css/extra.css
  - css/copy-button.css

extra_javascript:
  - js/copy-button.js  

theme: 
  name: readthedocs
  highlightjs: true
  logo: assets/logocaminas.png

markdown_extensions:
  - admonition
  - toc:
      permalink: True 
  - tables    
  - attr_list

nav:

- Componentes:
  - ðŸ”¹ Spring Framework: Spring.md
  - ðŸ”¹ Anotaciones: Anotaciones.md
  - ðŸ”¹ SpringBoot: SpringBoot.md
  - ðŸ”¹ Spring MVC: SpringMVC.md
  - ðŸ”¹ Spring Data: SpringData.md
  - ðŸ”¹ Docker: Docker.md
  