site_url : https://asalvadorc.github.io/AD_Componentes

site_name: AD - Acc√©s a Dades


extra_css:
  - css/extra.css
  - css/copy-button.css

extra_javascript:
  - js/copy-button.js  

theme: 
  name: readthedocs
  highlightjs: true
  logo: assets/logocaminas.png

markdown_extensions:
  - admonition
  - toc:
      permalink: True 
  - tables    
  - attr_list

nav:

- Componentes:
  - 1 - Spring: Spring.md
  - 2 - Anotaciones: Anotaciones.md
  - 3 - SpringBoot: SpringBoot.md
  - 4 - Spring MVC: SpringMVC.md
  - 5 - Spring Data: SpringData.md
  - 6 - Docker: Docker.md
  